sudo: required
services:
  - docker

before_install:
  - echo "Branch... $TRAVIS_BRANCH"
  - docker build -t registry.heroku.com/salilvnair-docker-react/web .


after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD" registry.heroku.com;
    docker push registry.heroku.com/salilvnair-docker-react/web;
    fi